// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {

    "browserframe": {
      name: "browserframe",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry//ui/browserframe.tsx"],
      component: React.lazy(() => import("@/registry/ui/browserframe.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "screen-1-example": {
      name: "screen-1-example",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry//example/screen-1.tsx"],
      component: React.lazy(() => import("@/registry/example/screen-1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "browserframe-example": {
      name: "browserframe-example",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry//example/browserframe-example.tsx"],
      component: React.lazy(() => import("@/registry/example/browserframe-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry//lib/utils.ts"],
      component: React.lazy(() => import("@/registry/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "screen-1": {
      name: "screen-1",
      type: "registry:section",
      registryDependencies: undefined,
      files: ["registry//section/screen-1.tsx"],
      component: React.lazy(() => import("@/registry/section/screen-1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
}
